[build.environment]
NODE_VERSION = "20"
AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless"]
included_files = ["node_modules/@netlify/blobs/**/*"]

# Schedule function
[functions."refresh-library"]
schedule = "0 */6 * * *"

# API Routes - ordem importa!
[[redirects]]
from = "/api/debug-sync"
to = "/.netlify/functions/debug-sync"
status = 200
force = true

[[redirects]]
from = "/api/debug-refresh"
to = "/.netlify/functions/debug-refresh"
status = 200
force = true

[[redirects]]
from = "/api/simple-refresh"
to = "/.netlify/functions/simple-refresh"
status = 200
force = true

[[redirects]]
from = "/api/test-setup"
to = "/.netlify/functions/test-setup"
status = 200
force = true

[[redirects]]
from = "/api/refresh"
to = "/.netlify/functions/refresh-library"
status = 200
force = true

[[redirects]]
from = "/api/snapshot"
to = "/.netlify/functions/snapshot"
status = 200
force = true

[[redirects]]
from = "/api/ping"
to = "/.netlify/functions/ping"
status = 200
force = true

[[redirects]]
from = "/api/games"
to = "/.netlify/functions/games"
status = 200
force = true

[[redirects]]
from = "/api/game/:id"
to = "/.netlify/functions/game/:id"
status = 200
force = true

# Page redirects
[[redirects]]
from = "/biblioteca"
to = "/biblioteca.html"
status = 200