[build.environment]
NODE_VERSION = "20"
AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless"]
included_files = ["node_modules/@netlify/blobs/**/*"]

# Schedule function
[functions."simple-sync"]
schedule = "0 2 * * *"

# API Routes - ordem importa!
[[redirects]]
from = "/api/simple-sync"
to = "/.netlify/functions/simple-sync"
status = 200
force = true

[[redirects]]
from = "/api/debug-sync"
to = "/.netlify/functions/debug-sync"
status = 200
force = true

[[redirects]]
from = "/api/quick-sync"
to = "/.netlify/functions/quick-sync"
status = 200
force = true

[[redirects]]
from = "/api/test-setup"
to = "/.netlify/functions/test-setup"
status = 200
force = true

[[redirects]]
from = "/api/test-steam"
to = "/.netlify/functions/test-steam"
status = 200
force = true

[[redirects]]
from = "/api/snapshot"
to = "/.netlify/functions/snapshot"
status = 200
force = true

[[redirects]]
from = "/api/games"
to = "/.netlify/functions/games"
status = 200
force = true

[[redirects]]
from = "/api/game/:id"
to = "/.netlify/functions/game/:id"
status = 200
force = true

# Page redirects
[[redirects]]
from = "/biblioteca"
to = "/biblioteca.html"
status = 200