[build.environment]
NODE_VERSION = "20"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless", "@netlify/blobs"]

# Schedule function - ajuste conforme necessário
[functions."refresh-library"]
schedule = "0 */6 * * *"  # A cada 6 horas

# API Routes
[[redirects]]
from = "/api/games"
to = "/.netlify/functions/games"
status = 200

[[redirects]]
from = "/api/game/*"
to = "/.netlify/functions/game/:splat"
status = 200

[[redirects]]
from = "/api/snapshot"
to = "/.netlify/functions/snapshot"
status = 200

[[redirects]]
from = "/api/ping"
to = "/.netlify/functions/ping"
status = 200

[[redirects]]
from = "/api/refresh"
to = "/.netlify/functions/refresh-library"
status = 200

# Page redirects
[[redirects]]
from = "/biblioteca"
to = "/biblioteca.html"
status = 200