[build.environment]
NODE_VERSION = "20"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless", "@netlify/blobs"]

[functions."refresh-library"]
# roda a cada 6 horas (UTC). Ajuste como quiser.
schedule = "0 */6 * * *"

[[redirects]]
from = "/api/games"
to = "/.netlify/functions/games"
status = 200

[[redirects]]
from = "/biblioteca"
to = "/biblioteca.html"
status = 200

[[redirects]]
from = "/api/game/*"
to = "/.netlify/functions/game/:splat"
status = 200

[[redirects]]
from = "/api/snapshot"
to = "/.netlify/functions/snapshot"
status = 200

[[redirects]]
from = "/api/ping"
to = "/.netlify/functions/ping"
status = 200



