[build.environment]
NODE_VERSION = "20"
AWS_LAMBDA_JS_RUNTIME = "nodejs20.x"

[functions]
node_bundler = "esbuild"
external_node_modules = ["@neondatabase/serverless"]

# Schedule function - sincronização automática da Biblioteca Familiar
[functions."family-sync"]
schedule = "0 2 * * *"

# API Routes - ordem importa!
[[redirects]]
from = "/api/family-sync"
to = "/.netlify/functions/family-sync"
status = 200
force = true

[[redirects]]
from = "/api/steam-sync"
to = "/.netlify/functions/steam-sync"
status = 200
force = true

[[redirects]]
from = "/api/test-basic"
to = "/.netlify/functions/test-basic"
status = 200
force = true

[[redirects]]
from = "/api/snapshot"
to = "/.netlify/functions/snapshot"
status = 200
force = true

[[redirects]]
from = "/api/games"
to = "/.netlify/functions/games"
status = 200
force = true

[[redirects]]
from = "/api/game/:id"
to = "/.netlify/functions/game/:id"
status = 200
force = true

# Page redirects
[[redirects]]
from = "/biblioteca"
to = "/biblioteca.html"
status = 200